config/routes.rb
Rails.application.routes.draw do

  root 'map_page#index'
  get '/' => 'map_page#index'
  get 'map/listView' => 'map_page#listView'
  get 'map/trendView' => 'map_page#trendsView'
  get 'api/web/data' => 'api_handeler#data'
  
  get 'api/web/getlistViewContent' => 'api_handeler#getlistViewContent'
  
  get 'api/mobile/data' => 'api_handeler#mobileData'
  
  
  resources :user
  get    'register'  => 'users#register'
  post   'register'  => 'users#register'
  get    'login'   => 'users#new'
  post   'login'   => 'users#new'
  get    'logout'  => 'users#destroy'
  get    'dashboard'    => 'users#dashboard'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/api_handeler_controller.rb
require 'soda/client'
class ApiHandelerController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    respond_to do |format|
      format.json # index.html.erb
    end
  end
  
  def data
    @lat = params[:lat]
    @lang = params[:lang]
    @radius = params[:radius]
    @from = params[:from]
    @to = params[:to]
    @type = params[:type]
    @arrest = params[:arrest]
    crimeType = params[:type].split(',')
    
    if @lat && @lang && @radius
      client = SODA::Client.new({ :domain => 'data.cityofchicago.org', :app_token => 'v1SkHrbzQcyFmlkL9D5W1UXfT' })
      @response = client.get('6zsd-86xi',
                              {"$select" => "arrest,case_number,date,description,location_description,latitude, longitude, primary_type, id",
                              "$where" => "within_circle(location, #{@lat}, #{@lang}, #{@radius}) AND
                                           date > '#{@from}' AND date < '#{@to}' And
                                           (primary_type = '#{crimeType[0]}' OR primary_type = '#{crimeType[1]}'
                                             OR primary_type = '#{crimeType[2]}' OR primary_type = '#{crimeType[3]}'
                                            )",
                              "$limit"=>"1200",
                              "arrest"=>"#{@arrest}",
                              }
                            )
      respond_to do |format|
        format.json { render :json => @response }
    end
        #if stale? last_modified: updated_at, etag: etag
        #  render json: @response
        #end  
    else
      @message ='{ "Error": { "status":400 , "message":"Please Specifiy the location co-ordinates and data limit" } }'
      respond_to do |format|
        format.json { render :json => @message }
      end 
    end
  end
  
  def getlistViewContent
    @lat = params[:lat]
    @lang = params[:lang]
    @radius = params[:radius]
    @from = params[:from]
    @to = params[:to]
    @type = params[:type]
    @arrest = params[:arrest]
    crimeType = params[:type].split(',')
  
    if @lat && @lang && @radius
      client = SODA::Client.new({ :domain => 'data.cityofchicago.org', :app_token => 'v1SkHrbzQcyFmlkL9D5W1UXfT' })
      @response = client.get('6zsd-86xi',
                              {
                              "$where" => "within_circle(location, #{@lat}, #{@lang}, #{@radius}) AND
                                           date > '#{@from}' AND date < '#{@to}' And
                                           (primary_type = '#{crimeType[0]}' OR primary_type = '#{crimeType[1]}'
                                             OR primary_type = '#{crimeType[2]}' OR primary_type = '#{crimeType[3]}'
                                            )",
                              "$limit"=>"1200",
                              "arrest"=>"#{@arrest}",
                              }
                            )
      #"$select" => "arrest,case_number,date,description,location_description,latitude, longitude, primary_type, id",
      respond_to do |format|
        format.json { render :json => @response }
      end 
    else
      @message ='{ "Error": { "status":400 , "message":"Please Specifiy the location co-ordinates and data limit" } }'
      respond_to do |format|
        format.json { render :json => @message }
      end 
    end
  end
  
  def mobileData
    headers['Access-Control-Allow-Origin'] = '*'
    @lat = params[:lat]
    @lang = params[:lang]
    @radius = params[:radius]
    @from = params[:from]
    @to = params[:to]
    @type = params[:type]
    @arrest = params[:arrest]
    datalimit = params[:datalimit]
    crimeType = params[:type].split(',')
  
    if @lat && @lang && @radius
      client = SODA::Client.new({ :domain => 'data.cityofchicago.org', :app_token => 'v1SkHrbzQcyFmlkL9D5W1UXfT' })
      response = client.get('6zsd-86xi',
                              {
                              "$where" => "within_circle(location, #{@lat}, #{@lang}, #{@radius}) AND
                                           date > '#{@from}' AND date < '#{@to}' And
                                           (primary_type = '#{crimeType[0]}' OR primary_type = '#{crimeType[1]}'
                                             OR primary_type = '#{crimeType[2]}' OR primary_type = '#{crimeType[3]}'
                                            )",
                              "$limit"=>"#{datalimit}",
                              "arrest"=>"#{@arrest}",
                              }
                            )
      respond_to do |format|
        format.json { render :json => response }
      end 
    else
      @message ='{ "Error": { "status":400 , "message":"Please Specifiy the location co-ordinates and data limit" } }'
      respond_to do |format|
        format.json { render :json => @message }
      end 
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #helper :all # include all helpers, all the time
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/map_page_controller.rb
class MapPageController < ApplicationController
  def index
    render 'index'
  end
  
  def trendsView
    render 'trendsView'
  end
  
  def listView
    render 'listview'
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :validate_authorization_for_user, only: [:dashboard]
 
  def new
    @user = User.new 
    if request.post?
        #Updated to use strong parameters
        @user = User.find_by({email: params[:user][:email]})
        if @user.authenticate(params[:user][:password_digest])
          log_in @user
          redirect_to dashboard_path
        else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
        end
    end
  end
  
  # show the user details after authentication
  def dashboard
     
  end
  
  #register the new user
  def register()
    @user = User.new
    if request.post?
      @user = User.new(user_params)
      if @user.save
        log_in @user
        redirect_to dashboard_path
      else
        render 'register'
      end
    else  
      render 'register'
    end
  end
  
  # logout the current user
  def destroy
    log_out
    redirect_to login_path
  end
  
  def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
  
  def validate_authorization_for_user
    redirect_to login_path unless current_user != nil 
  end
  
end

app/helpers/api_handeler_helper.rb
module ApiHandelerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_page_helper.rb
module MapPageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/api_handeler/index.html.erb
<h1>ApiHandeler#index</h1>
<p>Find me in app/views/api_handeler/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="AngularJsApp">
<head>
  <title>Crime reporting</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true"></script> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

<%= yield %>
  <!-- <%= debug(params) if Rails.env.development? %> -->
</body>
</html>

app/views/map_page/_template.html.erb
<div id="progress"><div id="progress-bar"><img src="<%= image_path("loader.gif") %>" alt="loader"/></div></div>
<div class="customLoader" ng-show="showLoder">
<img src="<%= image_path("loader.gif") %>" alt="loader"/>
</div>

<div id="wrapper" class="toggled">
<nav class="navbar navbar-inverse nav-bar-top">
               <div class="container-fluid">
           
                                  <div class="navbar-header">
                                    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">
                                        <button type="button" class="navbar-toggle tog_menu">
                                                   <span class="sr-only">Toggle navigation</span>
                                                   <span class="icon-bar"></span>
                                                   <span class="icon-bar"></span>
                                                   <span class="icon-bar"></span>
                                                 </button></a>
                                    <a class="navbar-brand logo-brand demo_logo" href="/"><img src="<%= image_path('chicago-logo.png') %>"/></a>
                                  </div>
                                                                                                    
                                  <div id="navbar" class="navbar-collapse navbar-right">
                                       <ul class="navbar-form nav navbar toolbar">
                                          <li class="filter-section"><a class="filter-added" href="#"><i class="fa fa-filter"></i></a>
                                          <div class="filter-desp" style="display: none;">
                                             <ul>
                                                            <li><p class="add">Time line</p></li>
                                                <li>
                                                              
                                                              <div id="slider"></div>
                                                          </li>
                                                          <li class="crm_type">
                                                           <p class="add">Crime Type</p>
                                                           <table>
                                                               <tr ng-repeat="data in crimeType">
                                                                    <td>
                                                                       <label> <input class="horrible-input" type="checkbox" checklist-model="search.type" checklist-value="data"> {{data}} </label>
                                                                    </td>
                                                               </tr>
                                                           </table>
                                                </li>
                                             </ul>
                                          </div>
                                          </li>
                                          <li>
                                             <form ng-submit="getAddress()">
                                                            <input type="search" id="search" placeholder="Search an address" ng-model="newPlaceAddress" />
                                                            <input type="submit" style="display: none;" />
                                             </form>
                                          </li>
                                          <li><button id="btn-search"><i class="fa fa-search"></i></button></li>
                                       </ul>
                                  </div>
                   

               </div>
</nav>
     <!--Tab section start here-->
 <!-- Sidebar -->
        <div id="sidebar-wrapper">
          <div class="top-wrapper-sidemenu"> 
             <h1><img src="<%= image_path('mission-notive.png') %>">Crime Reports</h1>
             <div class="col user-username">User Name</div>
          </div>

          <ul>
            <a href="javascript:void(0);"><li><i class="fa fa-file"></i>Submit a Tip</li></a>
            <a href="javascript:void(0);"><li><i class="fa fa-camera"></i>Register a Camera</li></a>
            <a href="javascript:void(0);"><li><i class="fa fa-sliders"></i>Setting</li></a>
            <a href="javascript:void(0);"><li><i class="fa fa-sign-in"></i>Sign Out</li></a>
          </ul>


        </div>
        <!-- /#sidebar-wrapper -->
        
<div class="container-fluid">
 <div class="row top-tabs">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation"><%= link_to 'Map', {:controller => 'map_page', :action => 'index'} %></li>
      <li role="presentation"><%= link_to 'Trend view', {:controller => 'map_page', :action => 'trendsView'} %></li>
      <li role="presentation"><%= link_to 'List view', {:controller => 'map_page', :action => 'listView'} %></li>
    </ul>
  </div>
</div>

<script>
$("#slider").dateRangeSlider();
var selector = '.nav li';
$(selector).on('click', function(){
    $(selector).removeClass('active');
    $(this).addClass('active');
});                      
</script>

<script>
$(document).ready(function(){
    $(".filter-added").click(function(){
        $(".filter-desp").slideToggle();
    });
});
</script>

app/views/map_page/index.html.erb
<section ng-controller="mainController" ng-init="getData()">
<%= render 'template' %> 

 <div id="mapPage">

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div id="map"></div>
            <div class="exclamation-sign"><a href="#"><i class="fa fa-exclamation-circle"></i></a></div>            
        </div>

        <section id="map-details" ng-show="clickedMarkerData.arrest !== '' ">
               <div class="container-fluid">
               
                              <div class="row map-popup">
                                  <div class="container">
                                    <button class="left_button" ng-click="previousMarker()" ng-show="disableNextPrevButton == false"><a href="javascript:void(0);"><i class="fa fa-caret-left"></i></a></button>
                                    <h3>{{saneLocationMarkerLength}}</h3>
                                    <button class="right_button" ng-click="NextMarker()" ng-show="disableNextPrevButton == false"><a href="javascript:void(0);"><i class="fa fa-caret-right"></i></a></button>
                                  </div>
                              </div>
               
                              <div class="row">
                                <div class="container">
                                <div class="crime-info">
                                  <ul>
                                    <li>
                                      <div class="col-md-1 user-info-icon">
                                        <img src="<%= image_path('map-user-crime.png') %>">             
                                      </div>
                                      <div class="col-md-10 user-desp-part">
                                        <h4>{{clickedMarkerData.primary_type}}</h4>
                                        <!--<p>{{clickedMarkerData.block}} <span>({{clickedMarkerData.description}})</span></p>-->
                                         <div class="table-user-info">
                                            <ul>
                                              <li><span>Date :</span> {{(clickedMarkerData.date | date:'yyyy-MM-dd')}}</li>
                                              <li><span>Time :</span> {{(clickedMarkerData.date | date:'hh:mm:ss a')}}</li>
                                              <li><span>Incident ID : </span> {{clickedMarkerData.id}}</li>
                                              <li><span>Case Number : </span> {{clickedMarkerData.case_number}}</li>
                                              <li><span>Agency : </span> Chicago Police Department</li>
                                              <li><span>Arest Made : </span> {{clickedMarkerData.arrest}}</li>
                                            </ul>
                                        </div> 
                                      </div>
                                      <div class="col-md-1 user-liking">
                                        <p>{{(clickedMarkerData.date | date:'yyyy-MM-dd')}}<span>{{(clickedMarkerData.date | date:'hh:mm:ss a')}}</span></p>
                                         <p class="comment-share"><a href="#"><img src="<%= image_path('tip-icon.png') %>"></a><a href="javascript:void(0);"><i class="fa fa-share"></i></a></p> 
                                      </div>
                                    </li>
                                  </ul>
                                </div>
                              </div>
                             </div>


               </div>
        </section>



        <!-- /#page-content-wrapper -->
   
    </div>
    <!-- /#wrapper -->
    
    
   </div> 
   
    
 </section>
 <script type="text/javascript">
    $("#slider").dateRangeSlider();
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    
    $(function () {
      $('input,textarea').focus(function () {
          $(this).data('placeholder', $(this).attr('placeholder'))
                 .attr('placeholder', '');
      }).blur(function () {
          $(this).attr('placeholder', $(this).data('placeholder'));
      });
    });
    
    ( function() {
      $('#btn-search').on('click', function(e) {
        e.preventDefault();
        $('#search').animate({width: 'toggle'}).focus();
    
      });
    } () );
    
 </script>
 

app/views/map_page/listview.html.erb
<section ng-controller="ListViewContoller" ng-init="listViewAction()">
<%= render 'template' %> 

 <div id="listViewPage">
       
      <div id="page-content-wrapper">
          <div class="container">
          <div class="list-view">
            <div class="row">
              <div class="crime-info">
                <ul>
                  <li ng-repeat = "data in listViewData">
                    <div class="col-md-1 user-info-icon">
                      <img src="<%= image_path('green-user.png') %>">             
                    </div>
                    <div class="col-md-10 user-desp-part">
                      <h4 ng-click="showDetailInfo($index)" style="cursor: pointer;">{{data.primary_type}}</h4>
                      <h3>{{data.block}}({{data.location_description}})</h3>
                      <div class="table-user-info" id="showInfo{{$index}}" style="display: none;">
                          <ul>
                            <li><span>Updated On :</span> {{(data.updated_on | date:'yyyy-MM-dd')}}</li>
                            <li><span>Updated At :</span> {{(data.updated_on | date:'hh:mm:ss a')}}</li>
                            <li><span>Incident ID : </span> {{data.id}}</li>
                            <li><span>Case Number : </span> {{data.case_number}}</li>
                            <li><span>Agency : </span> Chicago Police Department</li>
                            <li><span>Arest Made : </span> {{data.arrest}}</li>
                          </ul>
                      </div> 	
                    </div>
                    <div class="col-md-1 user-liking">
                       <p>{{(data.date | date:'yyyy-MM-dd')}}<span>{{(data.date | date:'hh:mm:ss a')}}</span></p> 
                      <p class="comment-share"><a href="javascript:void(0);"><img src="<%= image_path('tip-icon.png') %>"></a><a class="share-icon" href="javascript:void(0);"><i class="fa fa-share"></i></a></p> 
                    </div>
                  </li>
                </ul>
              </div>
            </div>

          </div>
          </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
    
  
 </section>
 <script type="text/javascript">
    $("#slider").dateRangeSlider();
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    
    $(function () {
      $('input,textarea').focus(function () {
          $(this).data('placeholder', $(this).attr('placeholder'))
                 .attr('placeholder', '');
      }).blur(function () {
          $(this).attr('placeholder', $(this).data('placeholder'));
      });
    });
    
    ( function() {
      $('#btn-search').on('click', function(e) {
        e.preventDefault();
        $('#search').animate({width: 'toggle'}).focus();
    
      });
    } () );
    
 </script>
    

app/views/map_page/trendsView.html.erb
<section ng-controller="TrendsController">
  <%= render 'template' %>
  
  <div id="page-content-wrapper">    
    <div class="container">
      <div class="list-view">
        <div class="row">
          <div class="card">
                  <div class="item item-divider">Chart for Week</div>
                  <div class="item item-text-wrap">
                          <canvas id="line" class="chart chart-line" data="graphWeek.data"
                                  labels="graphWeek.labels" options="{showTooltips: false}"></canvas>
                  </div>
          </div>
          <div class="card">
                  <div class="item item-divider">Chart for Day</div>
                  <div class="item item-text-wrap">
                          <canvas id="line" class="chart chart-line" data="graphDay.data"
                                  labels="graphDay.labels" options="{showTooltips: false}"></canvas>
                  </div>
          </div>
          <div class="card last-cards">
                  <div class="item item-divider">Chart for Month</div>
                  <div class="item item-text-wrap">
                          <canvas id="line" class="chart chart-line" data="graphMonth.data"
                                  labels="graphMonth.labels" options="{showTooltips: false}"></canvas>
                  </div>
          </div>         
        </div>
      </div>
      
    </div>
  </div>
</section>

 <script type="text/javascript">
    $("#slider").dateRangeSlider();
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    
    $(function () {
      $('input,textarea').focus(function () {
          $(this).data('placeholder', $(this).attr('placeholder'))
                 .attr('placeholder', '');
      }).blur(function () {
          $(this).attr('placeholder', $(this).data('placeholder'));
      });
    });
    
    ( function() {
      $('#btn-search').on('click', function(e) {
        e.preventDefault();
        $('#search').animate({width: 'toggle'}).focus();
    
      });
    } () );
    
 </script>

app/views/users/_form.html.erb
<%= form_for(@user, :session, url: login_path) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h1>Welcome to Dashboard</h1>
<h2>Current user: <%= current_user.name %></h2>

<p><%= link_to "Log out", logout_path, method: "destroy" %></p>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="image-setting">
<section id="register">
  <div class="container">
      <div class="inner-register">

        <% provide(:title, "Log in") %>
        <center><h1>Log in</h1></center>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= form_for(@user, url: login_path) do |f| %>
    
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
    
          <%= f.label :password %>
          <%= f.password_field :password_digest, class: 'form-control' %>
          <%= f.submit "Log in", class: "btn btn-primary" %>
          <p>New user? <%= link_to "Sign up now!", register_path %></p>
        <% end %>
        
</div>
</div>
</section>
</div>

app/views/users/register.html.erb
<div class="image-setting">
<section id="register">
  <div class="container">
      <div class="inner-register">
        <% provide(:title, 'Sign up') %>
        <center><h1>Sign Up For Free</h1></center>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                The form contains <%= @user.errors.count %> error.
              </div>
              <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        
          <%= form_for(@user, url: register_path) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name , class: 'form-control'%>

          <%= f.label :email %>
          <%= f.email_field :email , class: 'form-control'%>

          <%= f.label :password %>
          <%= f.password_field :password , class: 'form-control'%>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation , class: 'form-control'%>

          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
        </div>
  </div>
</section>
</div>